import React, { useRef } from 'react';
import { Canvas, useFrame } from '@react-three/fiber';
import { ScrollControls, useScroll, Float, Sparkles } from '@react-three/drei';

// A simple box generated by code (No external file needed)
function DebugCube() {
  const meshRef = useRef();
  const scroll = useScroll();

  useFrame((state, delta) => {
    // If this runs, your 3D engine is working
    if (!meshRef.current) return;
    
    // Rotate based on scroll
    const scrollOffset = scroll.offset || 0;
    meshRef.current.rotation.x = scrollOffset * Math.PI;
    meshRef.current.rotation.y = scrollOffset * Math.PI * 2;
    
    // Move slightly
    meshRef.current.position.x = -2 + (scrollOffset * 4);
  });

  return (
    <mesh ref={meshRef} scale={1.5}>
      <boxGeometry args={[1, 1, 1]} />
      <meshStandardMaterial color="orange" wireframe={true} />
    </mesh>
  );
}

function HTMLContent() {
  return (
    <ScrollControls pages={4} damping={0.2}>
      <Float speed={2} rotationIntensity={0.5} floatIntensity={0.5}>
        <DebugCube />
      </Float>
      
      {/* Simple Text Overlay */}
      <div style={{ position: 'absolute', top: 0, left: 0, width: '100%', height: '100%' }}>
        <div className="section"><h1>DEBUG MODE</h1><p>If you see the box, the code works.</p></div>
        <div className="section right"><h2>SCROLL DOWN</h2></div>
        <div className="section"><h2>KEEP SCROLLING</h2></div>
        <div className="section right"><h2>FINISH</h2></div>
      </div>
    </ScrollControls>
  );
}

export default function App() {
  return (
    <div style={{ width: '100vw', height: '100vh', background: '#080808' }}>
      <Canvas dpr={[1, 1]} camera={{ position: [0, 0, 6], fov: 50 }}>
        <ambientLight intensity={0.5} />
        <pointLight position={[10, 10, 10]} />
        <HTMLContent />
      </Canvas>
    </div>
  );
}